version: '3.8'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: Sql_server
    restart: always
    environment:
      - SA_PASSWORD=sqlserver_docker
      - ACCEPT_EULA=Y
      - hostname=sqlserver
    ports: [1433:1433]
  app:
    build: .
    container_name: library_API
    ports:
      - 3200:3200
      - 9229:9229
    links:
      - sqldata
    volumes:
      - .:/usr/app
    depends_on:
      - sqldata